# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
language: objective-c #1
osx_image: xcode9.2 #2

xcode_project: SwiftLintDemo.xcodeproj #3
xcode_scheme: SwiftLintDemo #4


# os: osx
# -before_install:
#  - |
#     gem install xcpretty -N --no-ri --no-rdoc