# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
language: objective-c #1
os: osx
osx_image: xcode9.2
xcode_project: SwiftLintDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: MyNewProjectTests

env:
  matrix:
    - TEST_TYPE=iOS
-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
after_success:
    - sleep 5
    - if [ "$TEST_TYPE" = iOS ] ; then
        bash <(curl -s https://codecov.io/bash)
      fi


# os: osx
# -before_install:
#  - |
#     gem install xcpretty -N --no-ri --no-rdoc